### ISSUE TITLE
Clean up dylink imports, refactor libraries

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/seattlelib_v2#137]
We currently pull Repy libraries into programs through [dylink](wiki:SeattleLib/dylink.repy)'s ```dy_import_module_symbols``` which is equivalent to Python's ```from X import *```. We [should better use](http://docs.python.org/2/howto/doanddont.html#from-module-import) ```dy_import_module``` which roughly corresponds to Python's ```import X as Y```:

```
# Python equivalent for ``import actual_library_name as desired_library_name''
desired_library_name = dy_import_module("actual_library_name.extension")

# Now we can access the library functions as expected
desired_library_name.some_function()
# etc.
```

The current way we name functions in our libraries is ```libraryprefix ``_'' functionname```, like ```advertise_lookup```. When we switch to ```dy_import_module```, we need to refactor our libraries to drop the prefix and underscore, e.g. ```advertise.lookup```.

**Comment by aaaaalbert** [comment]
`dylink` fixes are in place; I opened a new issue for the question of refactoring. Closing this issue!
