### ISSUE TITLE
Librepy files have not been updated...

### ISSUE THREAD

**Issue by JustinCappos** [SeattleTestbed/seattlelib_v2#147]
It looks like the librepy\* files have not been updated recently.  As such, they use operations like 'print' and also use the old dylink import format.  These do not work with trunk and thus cause any code using these to fail.

**Comment by aaaaalbert** [comment]
Fixed in 7ed321b364d3a3a49692f305ae2056119f04019c, 3815113851d454a0d3d9b4b9005c1e3bc06c7462, 2177f37e2f5e01cd38481eb5a8f5fcfb52bf4f1d. Closing.
