### ISSUE TITLE
[Unit Testing]: Possible Missing Test Condition in `ut_seattlelib_time_interface_updatetime_before_registermethod.r2py`

### ISSUE THREAD

**Issue by vladimir-v-diaz** [SeattleTestbed/seattlelib_v2#159]
`ut_seattlelib_time_interface_updatetime_before_registermethod.r2py`

The unit test above verifies that an exception is raised if `time_interface.time_updatetime()` is called before a time method is registered with `time_interface.time_register_method()` (a requirement of using time_interface.r2py):
https://github.com/SeattleTestbed/seattlelib_v2/blob/master/tests/ut_seattlelib_time_interface_updatetime_before_registermethod.r2py#L10-L14

It makes sense to assume that `time_register_method()` is not called if `ut_seattlelib_time_interface_updatetime_before_registermethod.r2py` is the only module that is executed, but does this assumption hold if this unit test is tested along with the others as a group?  What if a time method is registered in another module that this unit test imports?

Should this unit test raise an exception, or test failure, if `time_interface.time_updatetime()` *doesn't* raise an exception? (assuming, of course, that time_register_method() hasn't been called.)

**Comment by aaaaalbert** [comment]
Other processes / unit test scripts that call the time functions don't interfere with this script. They are all separate programs that don't share any active state.

The last observation is spot-on. The test absolutely must raise an error (or print a message) if `time_interface` doesn't complain. In the current version, both an expected error and no error at all lead to the same conclusion --- `PASS`.

**Comment by aaaaalbert** [comment]
@karthikgvss will work on this.

**Comment by aaaaalbert** [comment]
Fixed in 4c6a5a2c17117d68c8c3c3c0b90b6e1c5106881e / #160. Closing this issue.
