### ISSUE TITLE
Repeating `centralizedadvertise.r2py` and `centralizedadvertise_v2.r2py`. Problem with `advertiseserver_v2.poly.edu`

### ISSUE THREAD

**Issue by hieusydo** [SeattleTestbed/seattlelib_v2#182]
The two files `centralizedadvertise.r2py` and `centralizedadvertise_v2.r2py`are functionally the same except for different static variables. 

Also, attempt to announce a new pair in  `centralizedadvertise_2.r2py` raises `Exception (with class '.SocketTimeoutError'): recv() timed out!!` while the announcement is successful in  `centralizedadvertise.r2py`. After a discussion with Lukas, it seems that `advertiseserver_v2.poly.edu` is alive but does not open any port (ping-able but nmap times out).

**Comment by aaaaalbert** [comment]
Your advertise server test script should let you check that hypothesis, right?

**Comment by hieusydo** [comment]
@aaaaalbert Yes. My test script `sockettimeout.timeout_openconnection(gethostbyname(advertiseserver_v2.poly.edu, 10102, timeout=10)` runs successfully, which means that the server is alive on port 10102. I confirm by checking with `nmap advertiseserver_v2.poly.edu -p 10102`. And I still don't know why I cannot announce/lookup on that server on port 10102.
