### ISSUE TITLE
Delete obsolete seattlelib_v2.wiki

### ISSUE THREAD

**Issue by lukpueh** [SeattleTestbed/seattlelib_v2#185]
This is a PR disguised as an Issue (GitHub does not support PRs for Wiki changes).
The wiki of this repo currently consists of:
 - [Home.md](https://github.com/SeattleTestbed/seattlelib_v2/wiki) -- points to obsolete trac wiki
 - [Continuous-Integration-for-the-Team.md] (https://github.com/SeattleTestbed/seattlelib_v2/wiki/Continuous-Integration-for-the-Team) -- moved to [SeattleTestbed/docs](https://github.com/SeattleTestbed/docs) where it should be (cf. [#19](https://github.com/SeattleTestbed/docs/pull/19)) 
 - [How-to-Contribute.md] (https://github.com/SeattleTestbed/seattlelib_v2/wiki/How-to-Contribute) -- already in [docs/Contributing](https://github.com/SeattleTestbed/docs/tree/master/Contributing) where it waits for updates and conversions

So please go ahead and delete the wiki!

**Comment by aaaaalbert** [comment]
Fixed in these commits to the `seattlelib_v2.wiki` repo: 6d9096ebe369cfd08e8a91dffdb92a6e9d7fbaca, 3d95bfa38d12686b9a0e739dd58332b21105eb90, and a452f6c1c3704235535c8a13e79ee083eb884026.
