### ISSUE TITLE
Bug in wrapper.r2py where argument validity check for 'bool' type fails

### ISSUE THREAD

**Issue by rrgodhorus** [SeattleTestbed/seattlelib_v2#195]
In [wrapper.r2py](https://github.com/SeattleTestbed/seattlelib_v2/blob/master/wrapper.r2py#L460), there is a check: "match = isinstance(args[index], expected_types)” in line 460, which is supposed to check if each argument passed to a function matches the expected types. 
However, since bool is a subtype of int in python2, this test seems to accept booleans even if expected_types does not contain <type ‘bool’> .
Therefore, even though the reference monitor does type checking for its args like in "writeat": {"type": "func", "args": (str, (int, long)), "exceptions": Exception, "return": (int, type(None)), "target": LPFile.writeat}, passing True/False as writeat()’s second argument fails to be caught during safety check.

**Comment by JustinCappos** [comment]
Can you also check that no other types are subclasses of existing types?

**Comment by rrgodhorus** [comment]
> Can you also check that no other types are subclasses of existing types?

So you want me to replace isinstance() check with a direct type() check ?

**Comment by rrgodhorus** [comment]
I also noticed that the function return check (`_check_func_return`) has this behavior as well - https://github.com/SeattleTestbed/seattlelib_v2/blob/master/wrapper.r2py#L528. But this time only when return type is a single item (not a tuple).
Not sure why there's such a difference in implementation.

**Comment by JustinCappos** [comment]
Fixed by #196
